#!/usr/bin/python
# ups, package manager for linux-based operating systems (though I'm
# pretty sure it'd work on BSDs and derivatives and other Unix-likes)
# written by dbro and licensed under version 3 of the GNU General
# Public License.

# IMPORTS:

import sys
from os import chdir, remove
from urllib import urlopen
import tarfile
import bz2
import argparse

version = "0.5.1"

# BACKEND CODE:

binRepo = "http://www.sites.google.com/site/upspackagemanager/repository/bin/"
srcRepo = "http://www.sites.google.com/site/upspackagemanager/repository/src/"
pkgList = "/usr/share/ups-pkg-list.txt"
pkgDB = "http://www.sites.google.com/site/upspackagemanager/repository/ups-db.txt"

# Note to self: /etc/ups is where the _info text files are sent.

def pkginstall( pkg ):
	# This installs the specified package.
	filename = str(pkg)+".tar.bz2"
	address = binRepo+filename
	print "Downloading and extracting package..."
	archive = urlopen(address, 'r').read()
	chdir("/etc/ups")									# All of the credit here goes to Hollinski
	archive0 = open(filename, 'wb')
	archive0.write(archive)
	bz2.decompress(filename)
	archive1 = tarfile.open(filename, 'r')
	archive1.extractall()

def pkgremove( rmpkg ):
	# Removes the specified package.
	# Author's comments: This will be the easiest one to write (not that the other two were difficult.)
	chdir("/usr/bin")
	remove( rmpkg )
	chdir("/etc/ups")
	remove( rmpkg+"_info.txt" )

def showvers():
	print "ups"
	print "version "+str(version)

def showcredits():
	print "ups"
	print "\ndeveloped and programmed by draven stedman"
	print "with a bit of help from hollinski"
	
def pkgUpdate(pkg0):
	chdir("/usr/bin")
	remove( pkg0 )
	pkginstall( pkg0 )

def updateAllPackages():
	b = open(pkgList, 'r')
	for c in b:
		c = c.rstrip()
		pkgupdate(c)
		print "Update of package '"+c+"' completed."
	b.close()
	print "Update of all packages completed."

# FRONTEND CODE:

parser = argparse.ArgumentParser(description='ups package manager')

